### ISSUE TITLE
I don't think `supports_connect_get: false` works

### ISSUE THREAD

**Issue by mattrobenolt** [connectrpc/conformance#882]
While working on the Python implementation, I had this set in my config until I implemented:

See: https://github.com/mattrobenolt/connect-python/blob/ref/conformance/config.yaml#L16

But it's running tests such as `Connect with GET/HTTPVersion:1/Codec:CODEC_PROTO/TLS:false/success` which, I'd expect to not be attempted.

**Comment by perezd** [comment]
@jhump could you take a look into this when you have a moment?

**Comment by jhump** [comment]
Looks like the issue is the test case definition. It is missing an attribute. I'll have a fix momentarily.
