### ISSUE TITLE
Help needed: `error.details` `google.protobuf.Any`'s serialization format

### ISSUE THREAD

**Issue by igor-vovk** [connectrpc/conformance#948]
Hi!

I'm working on the https://github.com/igor-vovk/connect-rpc-scala library, which provides Connect-compatible server implementation for GRPC services written in Scala language.

While working on the conformance tests, I couldn't wrap my head around how `Any`'s should be serialized to Json so that Conformance tests will validate them as valid. [Current JSON-serialization implementation](https://github.com/scalapb/scalapb-json4s/blob/master/src/main/scala/scalapb/json4s/AnyFormat.scala#L46) that I'm using serializes `Any`'s as a message itself + `@type` field with the `typeUrl` value from `Any`. This seems to align with the specification, at least with [Java Protobuf specification](https://protobuf.dev/reference/java/api-docs/com/google/protobuf/Any.html):
```
The JSON representation of an `Any` value uses the regular
representation of the deserialized, embedded message, with an
additional field `@type` which contains the type URL.
```

So the JSON that is output by the server implementation in case of error looks like this:
```json
{
    "code": "unimplemented",
    "message": "unimplemented",
    "details": [
        {
            "@type": "type.googleapis.com/connectrpc.conformance.v1.ConformancePayload.RequestInfo",
            "requestHeaders": [
                {
                    "name": "connect-protocol-version",
                    "value": [
                        "1"
                    ]
                },
                {
                    "name": "content-type",
                    "value": [
                        "application/json"
                    ]
                },
                {
                    "name": "host",
                    "value": [
                        "127.0.0.1:34995"
                    ]
                },
                {
                    "name": "x-test-case-name",
                    "value": [
                        "Errors/HTTPVersion:1/Protocol:PROTOCOL_CONNECT/Codec:CODEC_JSON/Compression:COMPRESSION_IDENTITY/TLS:false/unary/unimplemented"
                    ]
                },
                {
                    "name": "user-agent",
                    "value": [
                        "connect-go/1.16.2 (go1.22.7) connectconformance-referenceclient/v1.0.4",
                        "grpc-java-inprocess/1.68.2"
                    ]
                },
                {
                    "name": "grpc-accept-encoding",
                    "value": [
                        "gzip"
                    ]
                }
            ],
            "requests": [
                {
                    "@type": "type.googleapis.com/connectrpc.conformance.v1.UnaryRequest",
                    "responseDefinition": {
                        "error": {
                            "code": "CODE_UNIMPLEMENTED",
                            "message": "unimplemented"
                        }
                    }
                }
            ]
        }
    ]
}
```

I've checked sources of `protobuf-es` library and it seems to do the same in terms of message structure. Well, what I'm getting from a Conformance test, is the following output, which is not very descriptive (it seems there are some details lost when Go JSON implementation deserializes JSON, and then it sets other fields to default values?):

```shell
#23 7.820 --------------------
#23 7.820 FAILED: Connect to HTTP Code Mapping/HTTPVersion:1/Codec:CODEC_JSON/Compression:COMPRESSION_IDENTITY/TLS:false/unary/unimplemented:
#23 7.820 	connect error JSON: details[0]: missing required key "value"
#23 7.820 	; actual error detail #1 does not match expected error detail: - wanted, + got
#23 7.820 	  (*anypb.Any)(Inverse(protocmp.Transform, protocmp.Message{
#23 7.820 	  	"@type":    s"google.protobuf.Any",
#23 7.820 	- 	"type_url": string("type.googleapis.com/connectrpc.conformance.v1.ConformancePayload.RequestInfo"),
#23 7.820 	+ 	"type_url": string("type.googleapis.com/"),
#23 7.820 	- 	"value":    s"{requests:[{[type.googleapis.com/connectrpc.conformance.v1.UnaryRequest]:{response_definition:{error:{code:CODE_UNIMPLEMENTED}}}}]}",
#23 7.820 	  }))
#23 7.820
#23 7.820 ---- HTTP Trace ----
#23 7.820  request>     0.000ms POST http://127.0.0.1:34995/connectrpc.conformance.v1.ConformanceService/Unary HTTP/1.1
#23 7.820  request>             Connect-Protocol-Version: 1
#23 7.820  request>             Content-Length: 62
#23 7.820  request>             Content-Type: application/json
#23 7.820  request>             Host: 127.0.0.1:34995
#23 7.820  request>             User-Agent: connect-go/1.16.2 (go1.22.7) connectconformance-referenceclient/v1.0.4
#23 7.820  request>             X-Test-Case-Name: Connect to HTTP Code Mapping/HTTPVersion:1/Codec:CODEC_JSON/Compression:COMPRESSION_IDENTITY/TLS:false/unary/unimplemented
#23 7.820  request>
#23 7.820  request>     0.144ms message #1: data: 62 bytes
#23 7.820  request>     0.144ms body end
#23 7.820 response<     8.807ms 501 Not Implemented
#23 7.820 response<             Connection: keep-alive
#23 7.820 response<             Content-Length: 795
#23 7.820 response<             Content-Type: application/json
#23 7.820 response<             Date: Sat, 30 Nov 2024 13:21:51 GMT
#23 7.820 response<
#23 7.820 response<     8.836ms message #1: data: 795 bytes
#23 7.820 response<     8.836ms body end
```

I've checked tests of the Conformance, but they seem to verify `Any` serialization only [against primitive values](https://github.com/connectrpc/conformance/blob/main/internal/app/connectconformance/results_test.go#L198), that should contain both `@type` and `value` fields.

So my question is, shouldn't a flat structure of `Any`'s be expected when reading `ConformancePayload.RequestInfo` messages? If not, what is the correct structure then? Thanks!

**Comment by timostamm** [comment]
Hey Ihor, you are correct about the JSON serialization of `google.protobuf.Any`. 

The type can store arbitrary messages by encoding them into a `bytes` field:

```proto
// the gist of google.protobuf.Any:
message Any {
  string type_url = 1;
  bytes value = 2;
}
```

When serialized to JSON, it's an object with the property `@type` for the type URL, and properties for all other fields of the message. For example:

```json
{
  "@type": "type.googleapis.com/example.Foo",
  "bar": 123
}
```

This JSON representation is convenient because all fields are human-readable, but there's a drawback: To serialize an `Any`, the message needs to be decoded from `Any.bytes` first. You need to know the schema to serialize an `Any` to JSON.

The Connect protocol was designed to be easy to transcode to gRPC. Transforming a Connect request to a gRPC request is simple - you just need to convert a couple of headers and message framing. To transform a gRPC response to a Connect response, it's the same - but only for the happy path. Connect error responses are always in JSON (similar to Twirp) because it's much easier to debug. But if the error details are using `google.protobuf.Any`, it suddenly becomes necessary to know the schema to transcode the response.

To avoid this problem (and to enable transcoding without knowledge of the schema), Connect error details have their own JSON representation. Similar to `Any`, it's the type name (but without any prefix), and message data in the Protobuf binary encoding (as base64):

```json
{
  "code": "unavailable",
  "message": "example",
  "details": [
    {
      "type": "example.Foo",
      "value": "CgIIPA"
    }
  ]
}
```

Optionally, servers can include a JSON representation in the `debug` property of a detail:

```diff
    {
      "type": "example.Foo",
      "value": "CgIIPA",
+     "debug": {"bar": 123}
    }
```

There are a few more details in the Connect protocol spec [here](https://connectrpc.com/docs/protocol#error-end-stream).

**Comment by igor-vovk** [comment]
Thanks for clarifying @timostamm, it does make much more sense now, and the format was indeed written in the docs 🤦‍♂️. The fix gave massive boost to the amount of successful tests.

Going to close the issue now.
